# Proxied ("orange cloud") A record in the Cloudflare-hosted parent zone,
# pointing at the nginx droplet. Cloudflare terminates public TLS and connects
# back to the origin on :443 — use SSL/TLS mode "Full" (the origin serves a
# self-signed certificate generated by cloud-init).
data "cloudflare_zone" "parent" {
  name = var.parent_domain
}

resource "cloudflare_record" "proxy" {
  zone_id = data.cloudflare_zone.parent.id
  name    = local.record_name
  type    = "A"
  content = digitalocean_droplet.proxy.ipv4_address
  proxied = true
  ttl     = 1 # 1 = automatic; required when proxied = true.
}
